# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# Removed runtime_version import for compatibility
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# Removed validation for compatibility with older protobuf versions
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"^\n\x0cStoryRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05genre\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\t\x12\x0c\n\x04tone\x18\x04 \x01(\t\x12\x12\n\ncharacters\x18\x05 \x01(\t\"\x1e\n\rStoryResponse\x12\r\n\x05story\x18\x01 \x01(\t\"3\n\x10TranslateRequest\x12\r\n\x05story\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"-\n\x11TranslateResponse\x12\x18\n\x10translated_story\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\" \n\x0eTopicsResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xc9\x01\n\x05\x41gent\x12:\n\rGenerateStory\x12\x13.agent.StoryRequest\x1a\x14.agent.StoryResponse\x12\x43\n\x0eTranslateStory\x12\x17.agent.TranslateRequest\x1a\x18.agent.TranslateResponse\x12?\n\x11GetTrendingTopics\x12\x13.agent.EmptyRequest\x1a\x15.agent.TopicsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORYREQUEST']._serialized_start=22
  _globals['_STORYREQUEST']._serialized_end=116
  _globals['_STORYRESPONSE']._serialized_start=118
  _globals['_STORYRESPONSE']._serialized_end=148
  _globals['_TRANSLATEREQUEST']._serialized_start=150
  _globals['_TRANSLATEREQUEST']._serialized_end=201
  _globals['_TRANSLATERESPONSE']._serialized_start=203
  _globals['_TRANSLATERESPONSE']._serialized_end=248
  _globals['_EMPTYREQUEST']._serialized_start=250
  _globals['_EMPTYREQUEST']._serialized_end=264
  _globals['_TOPICSRESPONSE']._serialized_start=266
  _globals['_TOPICSRESPONSE']._serialized_end=298
  _globals['_AGENT']._serialized_start=301
  _globals['_AGENT']._serialized_end=502
# @@protoc_insertion_point(module_scope)
